using Tests;
WordPossibilityTests tester = new WordPossibilityTests();
tester.ValidTest1();
tester.ValidTest2();
tester.ValidTest3();
tester.InvalidTest1();
tester.InvalidTest2();
tester.InvalidTest3();
tester.MixedTest1();
tester.MixedTest2();
tester.MixedTest3();
Console.WriteLine("\nTesting Finished.");
